name: Deploy API to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files for debugging
      run: |
        ls -la

    - name: Copy project to VPS and deploy
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: |
          ./Dockerfile
          ./dist
          ./package.json
          ./src
          ./node_modules
          ./package-lock.json
        target: "/var/www/tradeasia/api"

    - name: Set permissions on the VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Ensure the target directory exists and has the correct permissions
          mkdir -p /var/www/tradeasia/api
          chown -R $USER:$USER /var/www/tradeasia/api
          chmod -R 755 /var/www/tradeasia/api

    - name: Run Docker container on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/tradeasia/api
          docker stop api || true && docker rm api || true
          docker build -t tr-api .
          docker run -d -p 5000:5000 --name api tr-api
