name: Deploy Dockerized Express App to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Stop old container if exists
            docker stop tr-web-portal-server || true
            docker rm tr-web-portal-server || true
        
            # Remove old repo if exists
            rm -rf /var/www/tr-web-portal-server
        
            # Clone latest version
            git clone https://github.com/farukulwd/tr-web-portal-server.git /var/www/tr-web-portal-server
        
            cd /var/www/tr-web-portal-server
        
            # Build Docker image
            docker build -t tr-web-portal-server .
        
            # Run container
            docker run -d --name tr-web-portal-server -p 3000:3000 tr-web-portal-server
