name: Deploy API to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in the current directory
      run: |
        echo "Listing files in the workspace directory"
        ls -la /github/workspace

    - name: Set permissions on VPS target directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          mkdir -p /var/www/tradeasia/api
          chown -R $USER:$USER /var/www/tradeasia/api
          chmod -R 755 /var/www/tradeasia/api

    - name: Copy project to VPS and deploy
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "."
        target: "/var/www/tradeasia/api"

    - name: Run Docker container on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/tradeasia/api
          docker stop api || true && docker rm api || true
          docker build -t tr-api .
          docker run -d -p 5000:5000 --name api tr-api
