name: Deploy API to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/tr-api:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/tr-api:latest

    - name: List files in the current directory
      run: |
        echo "Listing files in the workspace directory"
        ls

    - name: Set permissions on VPS target directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          sudo mkdir -p /var/www/tradeasia/api
          sudo chown -R $USER:$USER /var/www/tradeasia/api
          sudo chmod -R 755 /var/www/tradeasia/api

    - name: Pull Docker image from Docker Hub and run on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/tradeasia/api
          docker pull ${{ secrets.DOCKER_USERNAME }}/tr-api:latest
          docker stop api || true && docker rm api || true
          docker run -d -p 5000:5000 --name api ${{ secrets.DOCKER_USERNAME }}/tr-api:latest
